project_name: globus-go-cli

before:
  hooks:
    - go mod tidy

builds:
  - id: globus
    binary: globus
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/scttfrdmn/globus-go-cli/cmd.Version={{.Version}}

archives:
  - id: tar
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - CONTRIBUTING.md
      - DESIGN.md
      - completions/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

brews:
  - name: globus-go-cli
    repository:
      owner: scttfrdmn
      name: homebrew-globus
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/scttfrdmn/globus-go-cli"
    description: "Command-line interface for Globus services, built in Go"
    license: "Apache-2.0"
    commit_author:
      name: Globus CLI Bot
      email: noreply@globus.org
    folder: Formula
    install: |
      bin.install "globus"
      # Generate and install shell completions
      output = Utils.popen_read("#{bin}/globus completion bash")
      (bash_completion/"globus").write output
      output = Utils.popen_read("#{bin}/globus completion zsh")
      (zsh_completion/"_globus").write output
      output = Utils.popen_read("#{bin}/globus completion fish")
      (fish_completion/"globus.fish").write output
    test: |
      assert_match "Globus CLI", shell_output("#{bin}/globus --version")

dockers:
  - image_templates:
      - "scttfrdmn/globus-go-cli:{{ .Version }}"
      - "scttfrdmn/globus-go-cli:latest"
    dockerfile: .github/docker/Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^feat[(\\w)]*:.*'
      order: 0
    - title: Bug Fixes
      regexp: '^fix[(\\w)]*:.*'
      order: 1
    - title: Others
      order: 999