name: Integration Tests

on:
  workflow_dispatch:  # Allow manual triggering
  schedule:
    - cron: '0 2 * * 1'  # Run weekly on Mondays at 2:00 UTC

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'scttfrdmn' }}  # Only run on main repo, not forks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Create .env.test
        run: |
          cat > .env.test << EOF
          # Globus Auth Credentials
          GLOBUS_TEST_CLIENT_ID=${{ secrets.GLOBUS_TEST_CLIENT_ID }}
          GLOBUS_TEST_CLIENT_SECRET=${{ secrets.GLOBUS_TEST_CLIENT_SECRET }}
          
          # Test Resource IDs (for transfer tests)
          GLOBUS_TEST_SOURCE_ENDPOINT=${{ secrets.GLOBUS_TEST_SOURCE_ENDPOINT }}
          GLOBUS_TEST_DESTINATION_ENDPOINT=${{ secrets.GLOBUS_TEST_DESTINATION_ENDPOINT }}
          GLOBUS_TEST_SOURCE_PATH=${{ secrets.GLOBUS_TEST_SOURCE_PATH }}
          GLOBUS_TEST_DESTINATION_PATH=${{ secrets.GLOBUS_TEST_DESTINATION_PATH }}
          
          # Test Identity (for identity lookup tests)
          GLOBUS_TEST_IDENTITY=${{ secrets.GLOBUS_TEST_IDENTITY }}
          EOF

      - name: Run integration tests
        run: make test-integration