# CI workflow for running tests
name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21.x, 1.22.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Install dependencies
      run: |
        go mod download
        go install golang.org/x/lint/golint@latest
    
    - name: Run linters
      run: |
        go vet ./...
        golint -set_exit_status ./...
    
    - name: Run unit tests with coverage
      run: go test -v -coverprofile=coverage.out -covermode=atomic ./...
    
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.out
        fail_ci_if_error: false
        flags: unit-tests

  integration-test:
    runs-on: ubuntu-latest
    if: ${{ false }}  # Disabled for now - enable when integration tests are ready
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21.x
    
    - name: Install dependencies
      run: go mod download
    
    - name: Run integration tests
      run: go test -v -tags=integration ./...
      env:
        GLOBUS_TEST_CLIENT_ID: ${{ secrets.GLOBUS_TEST_CLIENT_ID }}
        GLOBUS_TEST_CLIENT_SECRET: ${{ secrets.GLOBUS_TEST_CLIENT_SECRET }}